const choices = [
  " my wife",
  " my dog",
  " Australian shepherds",
  " Border collies",
  " tollers",
  " Irish setters",
  " golden retrievers",
  " cooking",
  " reading",
  " Cold War history",
  " books about sailing",
  " 20th century British children's literature",
  " playing the piano",
  " Kabalevsky",
  " Debussy",
  " Chopin",
  " Prokofiev",
  " Ravel",
  " Paramore",
  " Hayley Williams",
  " Chickapig",
  " Phil Bourassa's art",
  " The Legend of Zelda music",
  " Fire Emblem music",
  " Xenoblade Chronicles music",
  " Final Fantasy music",
  " Kirby's Return To Dreamland",
  " strawberry and cream Dr. Pepper",
  " orange vanilla coke",
  " Goldfish crackers",
  " Foster the People",
  " Jeeves and Wooster",
  " Rachmaninov",
  " Fire Emblem: Awakening",
  " Breath of the Wild",
  " Tears of the Kingdom",
  " woodworking",
  " electronic tinkering",
  " DC Comics",
  " DC animated movies",
  " planetariums",
  " sketchbooks",
  " Staedler pens",
  " leather messenger bags",
  " dark wood",
  " fishing",
  " gardening",
  " card/board games",
  " Avatar: The Last Airbender",
  " The Dragon Prince",
  " Godot",
  " Dominion",
  " my wife",
  " Wingspan",
  " DokuWiki",
  " Affinity Photo",
  " Espanso",
  " pad thai",
  " open source software",
  " PureRef",
  " Jellyfin",
  " MusicBee",
  " playing the organ",
  " paradise flycatchers",
  " scarves",
  " leather elbow patches",
  " Winco",
  " Costco",
  " Aldi",
  " chicken piccatta",
  " pannacotta",
  " tandoori chicken",
  " vindaloo",
  " Massaman curry",
  " pho",
  " clam chowder",
  " seafood",
  " sushi",
  " fog",
  " my wife",
  " misty weather",
  " rocky beaches",
  " mossy forests",
  " lava lamps",
  " tamarind",
  " salted food",
  " dark chocolate",
  " e-readers",
  " moss lawns",
  " bee-keeping",
  " Young Justice",
  " unions",
  " employee-owned companies",
  " Studio Ghibli",
  " pasta",
  " arugula",
  " Van Gogh",
  " Pre-Raphaelite art",
  " Monet",
  " Debussy",
  " old church organs",
  " aquariums",
  " hole-in-the-wall art galleries",
  " used books",
  " Legos",
  " K'next",
  " community organization",
  " SIGGRAPH papers",
  " public transit",
  " gouache painting",
  " Agatha Christie",
  " E. Nesbitt",
  " C. S. Lewis",
  " antique maps",
  " globes",
  " foxes",
  " U2",
  " Rush",
  " David Bowie",
  " Coldplay",
  " Ariana Grande",
  " small artists",
  " The Strokes",
  " Eleni Drake",
  " XP-Pen drawing tablets",
  " multi-monitor setups",
  " desk treadmills",
  " noise-cancelling headphones",
  " Sony WH-1000XM4 headphones",
  " mahogany",
  " MAKE Magazine",
  " Adafruit",
  " Raspberry Pi",
  " my wife",
  " fish and chips",
  " malt vinegar",
  " spumoni ice cream",
  " lightning storms",
  " thunderstorms",
  " Gorgonzola pasta",
  " warm lighting",
  " ducks",
  " otters",
  " deep sea exploration",
  " stargazing",
  " Paul Tillich",
  " Nightwing",
  " Spider-Man",
  " scientific progress",
  " Subarus",
  " Toyotas",
  " Psych",
  " public libraries",
  " Ruby",
  " PyQtGui",
  " DearPyGui",
  " Batgirl",
  " Batgirls",
  " Into/Across the Spiderverse",
  " squirrels",
  " Amsterdam",
  " Bristol",
  " the Pacific Northwest",
  " coastal Canada",
  " Vancouver",
  " Dutch bakeries",
  " Discourse",
  " Fire Emblem: Three Houses",
  " Super Smash Bros",
  " creme brulee",
  " rain",
  " exposed brick",
  " quiet places",
  " cafes",
  " orchids",
  " botanical gardens",
  " butterfly gardens",
  " public art",
  " Gilbert and Sullivan productions",
  " plays",
  " ballets",
  " concerts",
  " Thonny",
  " VS Code",
  " Honeyview",
  " Fire Emblem: Sacred Stones",
  " Mario Kart Wii",
  " houseplants",
  " fruit bats",
  " windmills",
  " Suki Waterhouse",
  " Pumpkin pie",
  " The Last Shadow Puppets",
  " The Arctic Monkeys",
  " Clairo",
  " Nirvana",
  " Beach House",
  " Walk the Moon",
  " Super Paper Mario",
  " college softball",
  " DIY automation",
  " Vue",
  " stargazing",
  " Converse Classic Chuck Taylors",
  " dark jeans",
  " J. Crew Factory",
  " backyard chicken coops",
]

export default choices
